language: php

php:
  - 5.6
  - 7.0
  - 7.1

matrix:
  allow_failures:
    - php: 7.1

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

install:
  - phpenv config-rm xdebug.ini || echo "xdebug is not installed"
  - travis_retry composer self-update && composer --version
  - travis_retry composer update --prefer-dist --no-interaction

script: vendor/bin/phpunit -v