#!/usr/bin/env php
<?php

define('APP_STARTED_AT', microtime(true));

$container = require(__DIR__ . '/bootstrap/container.php');

/* @var $container \Interop\Container\ContainerInterface */

$app = $container->get(\Symfony\Component\Console\Application::class);
/* @var $app \Symfony\Component\Console\Application */

$app->run();